apiVersion: v1
data:
  haSharedSecret: TWhOeVBEZjFscjlPZzVWWA==
  htpasswd: bWltaW46JDJhJDEwJHZla0liWnJYa0tCckJJLnVkQUtuMnU3T2NpN2hhZktIcXZ0UTN2ODB5T2FadWRZaE9VQW1l
kind: Secret
metadata:
  labels:
    app: docker-registry
  name: docker-registry-secret
  namespace: default
type: Opaque